[pytest]
addopts = -p no:warnings -sv --reruns=1 --only-rerun=TimeoutException --only-rerun=StaleElementReferenceException --only-rerun=ElementClickInterceptedException --only-rerun=InvalidSessionIdException

markers =
    smoke: Критичный функционал (быстрые тесты)
    regress: Полная регрессия
    e2e: End-to-End сценарии
    critical: Бизнес-критичные сценарии
    negative: Негативные сценарии
    slow: Тесты дольше 10 секунд
    flaky: Нестабильные тесты (карантин)
    role: Роль, под которой открывается приложение (используется фикстурой authorized_user)

filterwarnings =
    ignore::DeprecationWarning
    ignore::FutureWarning
    ignore::UserWarning
    ignore::RuntimeWarning
